[workspace]
members = [
  "apps/desktop/src-tauri",
  "crates/db",
  "crates/proxy-core",
  "crates/rule-engine",
  "crates/tls-manager",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "UNLICENSED"
version = "0.1.0"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"

