[package]
name = "pharles-desktop"
edition.workspace = true
license.workspace = true
version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = { version = "0.4", default-features = true, features = ["clock"] }
pharles-exporter = { path = "../../../crates/exporter" }
pharles-proxy-core = { path = "../../../crates/proxy-core" }
pharles-rule-engine = { path = "../../../crates/rule-engine" }
pharles-session-store = { path = "../../../crates/session-store" }
pharles-throttle-engine = { path = "../../../crates/throttle-engine" }
pharles-tls-manager = { path = "../../../crates/tls-manager" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tokio = { version = "1", features = ["sync"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Networking_WinInet"] }
winreg = "0.55"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
