export const WINDOWS_MENU_DEFINITIONS = [
  {
    id: "file",
    label: "File",
    items: [
      { id: "import_har", label: "Import HAR..." },
      { kind: "divider" },
      { id: "export_har", label: "Export as HAR..." },
      { kind: "divider" },
      { id: "clear_all_sessions", label: "Clear All Sessions" },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    items: [
      { id: "edit_undo", label: "Undo" },
      { id: "edit_redo", label: "Redo" },
      { kind: "divider" },
      { id: "edit_cut", label: "Cut" },
      { id: "edit_copy", label: "Copy" },
      { id: "edit_paste", label: "Paste" },
      { id: "edit_select_all", label: "Select All" },
      { kind: "divider" },
      { id: "find", label: "Find..." },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      { id: "refresh", label: "Refresh" },
      { kind: "divider" },
      { id: "goto_sessions", label: "Sessions" },
      { id: "goto_compose", label: "Compose" },
      { id: "goto_rules", label: "Rules" },
      { id: "goto_throttling", label: "Throttling" },
      { id: "goto_certificates", label: "Certificates" },
      { id: "goto_settings", label: "Settings" },
      { kind: "divider" },
      { id: "zoom_in", label: "Zoom In" },
      { id: "zoom_out", label: "Zoom Out" },
      { id: "zoom_reset", label: "Reset Zoom" },
      { kind: "divider" },
      { id: "theme_dark", label: "Dark Theme" },
      { id: "theme_light", label: "Light Theme" },
      { id: "theme_system", label: "Follow System Theme" },
    ],
  },
  {
    id: "proxy",
    label: "Proxy",
    items: [
      { id: "start_proxy", label: "Start Proxy" },
      { id: "stop_proxy", label: "Stop Proxy" },
      { kind: "divider" },
      { id: "toggle_system_proxy", label: "Toggle System Proxy" },
      { kind: "divider" },
      { id: "clear_sessions", label: "Clear Sessions" },
    ],
  },
  {
    id: "tools",
    label: "Tools",
    items: [
      { id: "breakpoint_rules", label: "Breakpoint Rules..." },
      { id: "throttling_tool", label: "Throttling..." },
      { kind: "divider" },
      { id: "install_cert", label: "Install Root Certificate" },
      { id: "cert_status", label: "Certificate Status" },
      { kind: "divider" },
      { id: "ios_quick_actions", label: "iOS Quick Actions" },
      { id: "android_quick_actions", label: "Android Quick Actions" },
      { kind: "divider" },
      { id: "adb_set_proxy", label: "Set Proxy via ADB" },
      { id: "adb_clear_proxy", label: "Clear Proxy via ADB" },
    ],
  },
  {
    id: "window",
    label: "Window",
    items: [
      { id: "window_minimize", label: "Minimize" },
      { id: "window_toggle_maximize", label: "Maximize" },
      { id: "window_toggle_fullscreen", label: "Toggle Full Screen" },
      { kind: "divider" },
      { id: "window_close", label: "Close Window" },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [
      { id: "check_for_updates", label: "Check for Updates..." },
      { kind: "divider" },
      { id: "documentation", label: "AIProxy Documentation" },
      { id: "show_logs", label: "Show Logs" },
      { id: "shortcuts", label: "Keyboard Shortcuts" },
    ],
  },
] as const;
